// <auto-generated />
using System;
using Hotel.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel.Migrations
{
    [DbContext(typeof(HotelContext))]
    partial class HotelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Hotel.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("EmployeeID ");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT")
                        .HasColumnName("FirstName ");

                    b.Property<string>("HireDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("HireDate ");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastName ");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Salary")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Salary ");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("Hotel.Model.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("GuestID ");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT")
                        .HasColumnName("FirstName ");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastName ");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT")
                        .HasColumnName("PhoneNumber ");

                    b.HasKey("GuestId");

                    b.ToTable("Guests ", (string)null);
                });

            modelBuilder.Entity("Hotel.Model.GuestService", b =>
                {
                    b.Property<int>("GuestServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("GuestServiceID ");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ReservationID ");

                    b.Property<string>("ServiceDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ServiceDate ");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ServiceID ");

                    b.HasKey("GuestServiceId");

                    b.ToTable("GuestServices ", (string)null);
                });

            modelBuilder.Entity("Hotel.Model.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PaymentID ");

                    b.Property<double?>("AmountPaid")
                        .HasColumnType("REAL")
                        .HasColumnName("AmountPaid ");

                    b.Property<string>("PaymentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("PaymentDate ");

                    b.Property<int>("ReservationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ReservationID ");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments ", (string)null);
                });

            modelBuilder.Entity("Hotel.Model.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ReservationID ");

                    b.Property<DateTime?>("CheckInDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("CheckInDate ");

                    b.Property<DateTime?>("CheckOutDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("CheckOutDate ");

                    b.Property<int>("GuestId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("GuestID ");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RoomID ");

                    b.HasKey("ReservationId");

                    b.ToTable("Reservations ", (string)null);
                });

            modelBuilder.Entity("Hotel.Model.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("RoomID ");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Capacity ");

                    b.Property<int>("PricePerNight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PricePerNight ");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RoomNumber ");

                    b.Property<string>("RoomType")
                        .HasColumnType("TEXT")
                        .HasColumnName("RoomType ");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms ", (string)null);
                });

            modelBuilder.Entity("Hotel.Model.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ServiceID ");

                    b.Property<string>("ServiceName")
                        .HasColumnType("TEXT")
                        .HasColumnName("ServiceName ");

                    b.Property<string>("ServicePrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("ServicePrice ");

                    b.HasKey("ServiceId");

                    b.ToTable("Services ", (string)null);
                });

            modelBuilder.Entity("Hotel.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserId ");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT")
                        .HasColumnName("Password ");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT")
                        .HasColumnName("UserName ");

                    b.HasKey("UserId");

                    b.ToTable("User", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
